### ISSUE TITLE
새로운 파일에 문제가 있습니다.

### ISSUE THREAD

**Issue by Hyun1108** [AnByoungHyun/verbose-adventure#1]
문제가 발생한 이미지 등록

![image](https://github.com/AnByoungHyun/verbose-adventure/assets/114565473/8b2347ea-0911-4a07-a5df-33d8e36f08d6)

**Comment by AnByoungHyun** [comment]
해당 이미지의 오류는 vagrant 에서 생성한 이미지가 제대로 삭제가 안되어서 발생 문제 입니다.

virtualBox 에서 해당 이미지를 지우고 다시 하세요.

**Comment by Hyun1108** [comment]
해결 완료 했습니다.
